### ISSUE TITLE
Issues with .fetch not returning data on first query.

### ISSUE THREAD

**Issue by Destreyf** [kamilkisiela/apollo-angular#1812]
**Describe the bug**
Calls to fetch never emit data while cache is empty.

I do not understand what's happening here, but it's become a blocker on my workflow.

When calling .watch().valueChanges I do get response data.

.fetch makes the network call, and If I log the output from my authentication interceptor, i see proper response data.

Furthermore, it appears that .fetch is populating the cache, if I make a second request, suddenly .fetch will return a result.

**To Reproduce**
I haven't been able to create a minimum reproduction yet, it seems to work fine on a basic install, I've reduced my configuration to be the same as a basic install and still run into problems.

**Expected behavior**
I would hope that .fetch would return data on the first request.

**Environment:**

```
├── @angular/cli@14.2.1
├── @angular/core@14.2.0
├── @apollo/client@3.6.9
├── apollo-angular@4.0.1
├── graphql@16.6.0
└── typescript@4.7.4
```

**Additional context**
I am still debugging this, but I am hoping someone else has run into this issue, or seen something, or maybe that I've just missed some big important section of the documentation.

This has brought this entire project to a complete standstill and I've been debugging it for over a week.

I am using GraphQL Code Generator with the following config:
```yaml
overwrite: true
generates:
  libs/client/graphql/src/lib/graphql.generated.ts:
    documents: 'libs/client/graphql/src/lib/**/documents/**/*.graphql'
    schema:
      - http://localhost:8888/v1/graphql:
    config:
      addExplicitOverride: true
    plugins:
      - add:
          content:
            - '/* eslint-disable @typescript-eslint/no-empty-interface */'
            - '/* eslint-disable @typescript-eslint/no-explicit-any */'
            - '/* cSpell:disable */'
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-apollo-angular':
          addExplicitOverride: true
          pureMagicComment: true
```

my GraphQL Module looks like this:

```ts
// ...imports

const uri = '/v1/graphql'; // <-- add the URL of the GraphQL server here
export function createApollo(httpLink: HttpLink): ApolloClientOptions<any> {
  return {
    link: httpLink.create({ uri }),
    cache: new InMemoryCache(),
  };
}

@NgModule({
  imports: [ApolloModule, HttpClientModule],
  exports: [ApolloModule],
})
export class ClientGraphQLModule {
  static forRoot(): ModuleWithProviders<ClientGraphQLModule> {
    return {
      ngModule: ClientGraphQLModule,
      providers: [
        {
          provide: APOLLO_OPTIONS,
          useFactory: createApollo,
          deps: [HttpLink],
        },
      ],
    };
  }
}
```

These config items seem to work just fine in a bare repository, so I'm going to guess this is something in my repo, but I have no idea where to begin to look as to why it's not returning data.
